global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'jaeger'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['jaeger:14269']
  - job_name: "aggregated-trace-metrics"
    static_configs:
      - targets: ['otel-collector:8889']
